apiVersion: v1
kind: Service
metadata:
  name: my-web-service
  labels:
    app: my-web-app
spec:
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000  # A port between 30000-32767
  type: NodePort       # Exposes the service externally via a port on each node
